logging:
  pattern:
    level: "[%level|${application.name:-}|${application.version:-}|${application.build:-}|%X{trace-id:-}]"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${logging.pattern.level:${LOG_LEVEL_PATTERN:-%5p}}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %.-10000m%.1ex{0}%replace(${LOG_EXCEPTION_CONVERSION_WORD:%rEx}){'\\R','\r'}%nopex%n"
  level:
    root: INFO

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      base-path: /admin-management
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      group:
        exploratory:
          include:
            - livenessState
            - readinessState
            - ping
          show-details: always
  health:
    enabled: true
    probes:
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: default
    import: "optional:configserver:http://configuration:8888"
  cloud:
    config:
      retry:
        max-interval: 60000
        initial-interval: 1000
        max-attempts: 20
        multiplier: 2

---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: "configserver:http://configuration:8888"
  cloud:
    config:
      retry:
        max-interval: 60000
        initial-interval: 1000
        max-attempts: 20
        multiplier: 2

grpc:
  client:
    message-service:
      address: static://localhost:9093
      negotiation-type: plaintext
  server:
    port: 9093
